#' Creates Disease Incidence Data Frame
#' @param .fd Data frame containing Fulcrum data
#' @noRd
.create_di_df <- function(.fd) {
  .fd %>%
    dplyr::select(fulcrum_id,
                  barley_fusarium_head_blightscab:describe_wheat_other) %>%
    tidyr::gather(key = disease,
                  value = incidence,
                  -fulcrum_id) %>%
    dplyr::mutate(
      disease =
        dplyr::recode(disease,
          barley_fusarium_head_blightscab = "fusarium head blight",
          barley_net_form_net_blotch = "net form net blotch",
          barley_spot_form_net_blotch = "spot form net blotch",
          barley_powdery_mildew = "powdery mildew",
          barley_stem_rust = "stem (black) rust",
          barley_virus = "virus",
          canola_powdery_mildew = "powdery mildew",
          canola_blackleg = "blackleg",
          canola_sclerotinia_stem_rot = "stem rot",
          virus_of_canola = "virus",
          chickpea_ascochyta_blight = "aschochyta blight",
          chickpea_botrytis_grey_mould = "botrytis grey mould",
          chickpea_fusarium_wilt = "fusarium wilt",
          chickpea_phytoplasma = "phytoplasma",
          chickpea_phytophthora_root_rot = "phytopthora root rot",
          chickpea_virus = "virus",
          maize_bacterial_stalk_rot_and_bacterial_top_rot =
            "bacterial stalk and top rot",
          maize_charcoal_rot = "charcoal rot",
          maize_common_rust = "common rust",
          maize_commonboil_smut = "boil smut",
          maize_crazy_top = "crazy top",
          maize_damping_off = "damping off",
          maize_diplodia_cob_rot = "diplodia cob rot",
          maize_downy_mildew = "downy mildew",
          maize_fusarium_ear_rot = "fusarium ear rot",
          maize_fusarium_stalk_rot = "fusarium stalk rot",
          maize_head_smut = "head smut",
          maize_pythium_stalk_rot = "pythium stalk rot",
          maize_turcica_leaf_blight = "turica leaf blight",
          maize_maydis_leaf_blight = "maydis leaf blight",
          maize_southern_rust = "southern rust",
          maize_virus = "virus",
          mungbean_alternaria_leaf_spot = "alternaria leaf spot",
          mungbean_bacterial_blight = "bacterial leaf blight",
          mungbean_charcoal_rot = "charcoal rot",
          mungbean_damping_off = "damping off",
          mungbean_fusarium_wilt = "fusarium wilt",
          mungbean_gummy_pod = "gummy pod",
          mungbean_halo_blight = "halo blight",
          mungbean_phytoplasma = "phytoplasma",
          mungbean_powdery_mildew = "powdery mildew",
          mungbean_puffy_pod = "puffy pod",
          mungbean_rhizoctonia_rot = "rhizoctonia rot",
          mungbean_root_lesion_nematode = "root lesion nematode",
          mungbean_sclerotinia_stem_rot = "sclerotinia stem rot",
          mungbean_sclerotium_stem_rot = "sclerotium stem rot",
          mungbean_tan_spot = "tan spot",
          mungbean_tsv = "Tobacco Streak Virus",
          mungbean_virus = "virus",
          peanut_fusarium_root_rot = "fusarium root rot",
          peanut_neocosmospora_root_rot = "neocosmospora root rot",
          peanut_net_blotch = "net blotch",
          peanut_kernel_shrivel_syndrome = "peanut kernel shrivel syndrome",
          peanut_root_lesion_nematode = "root lesion nematode",
          peanut_rust = "rust",
          peanut_sclerotium_base_rot = "sclerotium base rot",
          peanut_tsv = "Tobacco Streak Virus",
          peanut_virus = "virus",
          sorghum_bacterial_top_and_stalk_rot = "bacterial top and stalk rot",
          sorghum_charcoal_rot = "charcoal rot",
          sorghum_damping_off = "damping off",
          sorghum_ergot = "ergot",
          sorghum_fusarium_head_blight = "fusarium head blight",
          sorghum_fusarium_stalk_rot = "fusarium stalk rot",
          sorghum_grain_mould = "grain mould",
          sorghum_head_smut = "head smut",
          sorghum_johnsongrass_mosaic_virus = "Johnsongrass Mosaic Virus",
          sorghum_leaf_blight = "leaf blight",
          sorghum_root_lesion_nematode = "root lesion nematode",
          sorghum_rust = "rust",
          sorghum_sclerotium_base_rot = "sclerotium base rot",
          sorghum_tar_spot = "tar spot",
          soybean_bacterial_blight_bacterial_pustule =
            "bacterial blight pustule",
          soybean_charcoal_rot = "charcoal rot",
          soybean_damping_off = "damping off",
          soybean_peanut_mottle_virus = "Peanut Mottle Virus",
          soybean_phomopsis_seed_decay = "phomopsis seed decay",
          soybean_phytophthora_root_stem_and_root_rot =
            "phytophthora root and stem rot",
          soybean_phytoplasma = "phytoplasma",
          soybean_pod_stem_cankerblight = "pod and stem canker/blight",
          soybean_powdery_mildew = "powdery mildew",
          soybean_purple_seed_stain = "purple seed stain",
          soybean_rhizoctonia_rot = "rhizoctonia rot",
          soybean_root_lesion_nematode = "root lesion nematode",
          soybean_rust = "rust",
          soybean_sclerotinia_rot = "sclerotinia rot",
          soybean_mosaic_virus = "Soybean Mosaic Virus",
          soybean_virus = "virus",
          sunflower_apical_chlorosis = "apical chlorosis",
          sunflower_botrytis_head_rot_grey_mould =
            "botrytis head rot or grey mould",
          sunflower_charcoal_rot = "charcoal rot",
          sunflower_powdery_mildew = "powdery mildew",
          sunflower_rhizopus_head_rot = "rhizopus head rot",
          sunflower_rust = "rust",
          sunflower_sclerotinia_rot = "sclerotinia rot",
          sunflower_sclerotium_base_rot = "sclerotium base rot",
          sunflower_stem_cankerblight = "stem canker and blight",
          sunflower_tsv = "Tobacco Streak Virus",
          sunflower_verticillium_wilt = "verticillium wilt",
          wheat_fusarium_head_blightscab = "fusarium head blight",
          wheat_crown_rot = "crown rot",
          wheat_common_root_rot = "common root rot",
          wheat_leafbrown_rust = "leaf (brown) rust",
          wheat_root_lesion_nematode = "root lesion nematode",
          wheat_septoria_nodorum_blotch = "septoria nodorum blotch",
          wheat_stemblack_rust = "stem (black) rust",
          wheat_stripeyellow_rust = "stripe (yellow) rust",
          wheat_yellow_spot = "yellow spot",
          wheat_white_grain = "white grain"
        )
    )
}